/// Authoritative Linux package-to-CVE mappings normalized from Canonical, Red Hat, and Debian security sources.
table dim_linux_patch_cve_mapping
	isHidden

	column distribution
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: distribution

	column release_codename
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: release_codename

	column package_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: package_name

	column package_version
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: package_version

	column advisory_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: advisory_id

	column cve_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: cve_id

	column severity
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: severity

	column product
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: product

	column published_at
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceColumn: published_at

	column mapping_source
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: mapping_source

	column source_url
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: source_url

	partition dim_linux_patch_cve_mapping = m
		mode: import
		source =
				let
				    SupportedUbuntuReleases = {"noble", "jammy", "focal"},
				    SupportedRhelReleases = {"10", "9", "8", "7"},
				    SupportedDebianReleases = {"trixie", "bookworm", "bullseye"},
				    RetryableStatusCodes = {429, 500, 502, 503, 504},
				    CutoffDate = Date.AddMonths(Date.From(DateTimeZone.UtcNow()), -24),
				    RpmArchitectures = {"x86_64", "aarch64", "ppc64le", "s390x", "noarch", "i686"},
				    NormalizeRpmVersion = (value as any) as text =>
				        let
				            Version = Text.Trim(Text.From(value)),
				            WithoutArchitecture = List.Accumulate(RpmArchitectures, Version, (state as text, architecture as text) => if Text.EndsWith(Text.Lower(state), "." & architecture) then Text.Start(state, Text.Length(state) - Text.Length(architecture) - 1) else state)
				        in
				            if Text.StartsWith(WithoutArchitecture, "0:") then Text.AfterDelimiter(WithoutArchitecture, ":") else WithoutArchitecture,
				    UbuntuRelevantRows =
				        Table.SelectRows(
				            view_missing_patches,
				            each Text.Lower(Text.Trim(Text.From([os_type]))) = "linux"
				                and [os_distribution] = "Ubuntu"
				                and List.Contains(SupportedUbuntuReleases, Text.Lower(Text.Trim(Text.From([release_codename]))))
				                and [patch_name] <> null and Text.Trim(Text.From([patch_name])) <> ""
				                and [package_version] <> null and Text.Trim(Text.From([package_version])) <> ""
				        ),
				    UbuntuPatchKeys =
				        List.Buffer(
				            List.Distinct(
				                List.Transform(
				                    Table.ToRecords(UbuntuRelevantRows),
				                    each Text.Lower(Text.Trim(Text.From([release_codename]))) & "|" & Text.Lower(Text.Trim(Text.From([patch_name]))) & "|" & Text.Trim(Text.From([package_version]))
				                )
				            )
				        ),
				    UbuntuPatchKeySet = Record.FromList(List.Repeat({true}, List.Count(UbuntuPatchKeys)), UbuntuPatchKeys),
				    UbuntuPageSize = 20,
				    FetchUbuntuPage = (offset as number, optional attempt as nullable number) as record =>
				        let
				            CurrentAttempt = if attempt = null then 0 else attempt,
				            Response = try Web.Contents("https://ubuntu.com", [RelativePath = "security/notices.json", Query = [limit = Text.From(UbuntuPageSize), offset = Text.From(offset), order = "newest"], Headers = [Accept = "application/json"], ManualStatusHandling = RetryableStatusCodes]) otherwise null,
				            Status = if Response = null then 0 else Record.FieldOrDefault(Value.Metadata(Response), "Response.Status", 200),
				            Result = if Status = 200 then Json.Document(Response) else if CurrentAttempt < 3 then Function.InvokeAfter(() => @FetchUbuntuPage(offset, CurrentAttempt + 1), #duration(0, 0, 0, Number.Power(2, CurrentAttempt + 1))) else error Error.Record("CanonicalSecurityFeedUnavailable", "Canonical Ubuntu Security Notices could not be retrieved after four attempts.", [Offset = offset, Status = Status])
				        in
				            Result,
				    GetRecentUbuntuNotices = () as list =>
				        let
				            Pages =
				                List.Generate(
				                    () => [Offset = 0, Payload = FetchUbuntuPage(0)],
				                    each [Payload] <> null,
				                    each
				                        let
				                            Notices = Record.FieldOrDefault([Payload], "notices", {}),
				                            PublishedDates = List.RemoveNulls(List.Transform(Notices, each try Date.From(DateTimeZone.FromText(Text.From(_[published]))) otherwise null)),
				                            OldestPublished = if List.IsEmpty(PublishedDates) then #date(1900, 1, 1) else List.Min(PublishedDates),
				                            NextOffset = [Offset] + UbuntuPageSize,
				                            NextPayload = if List.Count(Notices) = UbuntuPageSize and OldestPublished >= CutoffDate then FetchUbuntuPage(NextOffset) else null
				                        in
				                            [Offset = NextOffset, Payload = NextPayload],
				                    each Record.FieldOrDefault([Payload], "notices", {})
				                ),
				            Notices = List.Combine(Pages)
				        in
				            List.Select(Notices, each let Published = try Date.From(DateTimeZone.FromText(Text.From(_[published]))) otherwise null in Published <> null and Published >= CutoffDate),
				    UbuntuNotices = if List.IsEmpty(UbuntuPatchKeys) then {} else List.Buffer(GetRecentUbuntuNotices()),
				    UbuntuRows =
				        List.Combine(
				            List.Transform(
				                SupportedUbuntuReleases,
				                (release as text) =>
				                    List.Combine(
				                        List.Transform(
				                            UbuntuNotices,
				                            (notice as record) =>
				                                let
				                                    AdvisoryId = Text.From(Record.FieldOrDefault(notice, "id", "")),
				                                    Product = Text.From(Record.FieldOrDefault(notice, "title", "")),
				                                    Published = try DateTime.From(DateTimeZone.FromText(Text.From(notice[published]))) otherwise null,
				                                    CveIds = Record.FieldOrDefault(notice, "cves_ids", {}),
				                                    ReleasePackages = Record.FieldOrDefault(notice, "release_packages", []),
				                                    Packages = if Record.HasFields(ReleasePackages, release) then Record.Field(ReleasePackages, release) else {},
				                                    BinaryPackages = List.Select(Packages, each try Record.FieldOrDefault(_, "is_source", true) = false and Record.HasFields(UbuntuPatchKeySet, release & "|" & Text.Lower(Text.Trim(Text.From(_[name]))) & "|" & Text.Trim(Text.From(_[version]))) otherwise false)
				                                in
				                                    List.Combine(List.Transform(BinaryPackages, (package as record) => List.Transform(CveIds, (cve as text) => [distribution = "Ubuntu", release_codename = release, package_name = Text.Lower(Text.Trim(Text.From(package[name]))), package_version = Text.Trim(Text.From(package[version])), advisory_id = AdvisoryId, cve_id = Text.Upper(Text.Trim(cve)), severity = "Unknown", product = Product, published_at = Published, mapping_source = "Canonical USN", source_url = "https://ubuntu.com/security/notices/" & AdvisoryId])))
				                        )
				                    )
				            )
				        ),
				    RhelRelevantRows =
				        Table.Buffer(
				            Table.SelectRows(
				                view_missing_patches,
				                each Text.Lower(Text.Trim(Text.From([os_type]))) = "linux"
				                    and [os_distribution] = "Red Hat Enterprise Linux"
				                    and List.Contains(SupportedRhelReleases, Text.Trim(Text.From([release_codename])))
				                    and [patch_name] <> null and Text.Trim(Text.From([patch_name])) <> ""
				                    and [package_version] <> null and Text.Trim(Text.From([package_version])) <> ""
				            )
				        ),
				    RhelPackages = List.Buffer(List.Distinct(List.Transform(Table.Column(RhelRelevantRows, "patch_name"), each Text.Lower(Text.Trim(Text.From(_)))))),
				    RedHatPageSize = 1000,
				    FetchRedHatPage = (packageName as text, page as number, optional attempt as nullable number) as list =>
				        let
				            CurrentAttempt = if attempt = null then 0 else attempt,
				            Response = try Web.Contents("https://access.redhat.com", [RelativePath = "hydra/rest/securitydata/csaf.json", Query = [package = packageName, after = Date.ToText(CutoffDate, [Format = "yyyy-MM-dd", Culture = "en-US"]), per_page = Text.From(RedHatPageSize), page = Text.From(page), isCompressed = "false"], Headers = [Accept = "application/json"], ManualStatusHandling = RetryableStatusCodes]) otherwise null,
				            Status = if Response = null then 0 else Record.FieldOrDefault(Value.Metadata(Response), "Response.Status", 200),
				            Result = if Status = 200 then Json.Document(Response) else if CurrentAttempt < 3 then Function.InvokeAfter(() => @FetchRedHatPage(packageName, page, CurrentAttempt + 1), #duration(0, 0, 0, Number.Power(2, CurrentAttempt + 1))) else error Error.Record("RedHatSecurityFeedUnavailable", "The Red Hat CSAF package query could not be retrieved after four attempts.", [Package = packageName, Page = page, Status = Status])
				        in
				            Result,
				    GetRedHatAdvisories = (packageName as text) as list =>
				        List.Combine(
				            List.Generate(
				                () => [Page = 1, Payload = FetchRedHatPage(packageName, 1)],
				                each [Payload] <> null,
				                each [Page = [Page] + 1, Payload = if List.Count([Payload]) = RedHatPageSize then FetchRedHatPage(packageName, [Page] + 1) else null],
				                each [Payload]
				            )
				        ),
				    ParseReleasedPackage = (packageName as text, packageNevra as text) as nullable record =>
				        let
				            Prefix = packageName & "-",
				            Remainder = if Text.StartsWith(Text.Lower(packageNevra), Text.Lower(Prefix)) then Text.Range(packageNevra, Text.Length(Prefix)) else "",
				            HasEpoch = Text.Contains(Remainder, ":"),
				            Epoch = if HasEpoch then Text.BeforeDelimiter(Remainder, ":") else "",
				            IsExactPackage = Epoch <> "" and Text.Select(Epoch, {"0".."9"}) = Epoch,
				            Architecture = if IsExactPackage and Text.Contains(Remainder, ".") then Text.AfterDelimiter(Remainder, ".", {0, RelativePosition.FromEnd}) else "",
				            VersionWithEpoch = if Architecture <> "" then Text.BeforeDelimiter(Remainder, ".", {0, RelativePosition.FromEnd}) else "",
				            Release = if Text.Contains(Text.Lower(packageNevra), ".el10") then "10" else if Text.Contains(Text.Lower(packageNevra), ".el9") then "9" else if Text.Contains(Text.Lower(packageNevra), ".el8") then "8" else if Text.Contains(Text.Lower(packageNevra), ".el7") then "7" else ""
				        in
				            if IsExactPackage and Text.Lower(Architecture) <> "src" and Release <> "" then [version = VersionWithEpoch, release = Release] else null,
				    RedHatRows =
				        List.Combine(
				            List.Transform(
				                RhelPackages,
				                (packageName as text) =>
				                    let
				                        PackageTargets = Table.SelectRows(RhelRelevantRows, each Text.Lower(Text.Trim(Text.From([patch_name]))) = packageName),
				                        Advisories = GetRedHatAdvisories(packageName)
				                    in
				                        List.Combine(
				                            List.Transform(
				                                Advisories,
				                                (advisory as record) =>
				                                    let
				                                        AdvisoryId = Text.Upper(Text.Trim(Text.From(Record.FieldOrDefault(advisory, "RHSA", "")))),
				                                        Severity = Text.Proper(Text.Lower(Text.Trim(Text.From(Record.FieldOrDefault(advisory, "severity", "Unknown"))))),
				                                        Published = try DateTime.From(DateTimeZone.FromText(Text.From(Record.FieldOrDefault(advisory, "released_on", null)))) otherwise null,
				                                        CveIds = Record.FieldOrDefault(advisory, "CVEs", {}),
				                                        ReleasedPackages = Record.FieldOrDefault(advisory, "released_packages", {}),
				                                        ParsedPackages = List.RemoveNulls(List.Transform(ReleasedPackages, each ParseReleasedPackage(packageName, Text.From(_)))),
				                                        SourceUrl = "https://access.redhat.com/errata/" & AdvisoryId
				                                    in
				                                        List.Combine(
				                                            List.Transform(
				                                                ParsedPackages,
				                                                (releasedPackage as record) =>
				                                                    let
				                                                        Release = Text.From(releasedPackage[release]),
				                                                        FixedVersion = Text.From(releasedPackage[version]),
				                                                        MatchingTargets = Table.SelectRows(PackageTargets, each Text.Trim(Text.From([release_codename])) = Release and NormalizeRpmVersion([package_version]) = NormalizeRpmVersion(FixedVersion))
				                                                    in
				                                                        List.Combine(List.Transform(Table.ToRecords(MatchingTargets), (target as record) => List.Transform(CveIds, (cve as text) => [distribution = "Red Hat Enterprise Linux", release_codename = Release, package_name = packageName, package_version = Text.Trim(Text.From(target[package_version])), advisory_id = AdvisoryId, cve_id = Text.Upper(Text.Trim(cve)), severity = Severity, product = "Red Hat Enterprise Linux " & Release, published_at = Published, mapping_source = "Red Hat CSAF", source_url = SourceUrl])))
				                                            )
				                                        )
				                            )
				                        )
				            )
				        ),
				    DebianRelevantRows =
				        Table.Buffer(
				            Table.SelectRows(
				                view_missing_patches,
				                each Text.Lower(Text.Trim(Text.From([os_type]))) = "linux"
				                    and [os_distribution] = "Debian GNU/Linux"
				                    and List.Contains(SupportedDebianReleases, Text.Lower(Text.Trim(Text.From([release_codename]))))
				                    and [patch_name] <> null and Text.Trim(Text.From([patch_name])) <> ""
				                    and [package_version] <> null and Text.Trim(Text.From([package_version])) <> ""
				            )
				        ),
				    DebianPackages = List.Buffer(List.Distinct(List.Transform(Table.Column(DebianRelevantRows, "patch_name"), each Text.Lower(Text.Trim(Text.From(_)))))),
				    FetchDebianPackageMetadata = (packageName as text, optional attempt as nullable number) as list =>
				        let
				            CurrentAttempt = if attempt = null then 0 else attempt,
				            Response = try Web.Contents("https://snapshot.debian.org", [RelativePath = "mr/binary/" & Uri.EscapeDataString(packageName) & "/", Headers = [Accept = "application/json"], ManualStatusHandling = RetryableStatusCodes]) otherwise null,
				            Status = if Response = null then 0 else Record.FieldOrDefault(Value.Metadata(Response), "Response.Status", 200),
				            Result = if Status = 200 then Record.FieldOrDefault(Json.Document(Response), "result", {}) else if CurrentAttempt < 3 then Function.InvokeAfter(() => @FetchDebianPackageMetadata(packageName, CurrentAttempt + 1), #duration(0, 0, 0, Number.Power(2, CurrentAttempt + 1))) else error Error.Record("DebianSnapshotUnavailable", "Debian Snapshot package metadata could not be retrieved after four attempts.", [Package = packageName, Status = Status])
				        in
				            Result,
				    DebianPackageMetadata = Record.FromList(List.Transform(DebianPackages, each List.Buffer(FetchDebianPackageMetadata(_))), DebianPackages),
				    DebianResolvedTargets =
				        List.RemoveNulls(
				            List.Transform(
				                Table.ToRecords(DebianRelevantRows),
				                (target as record) =>
				                    let
				                        PackageName = Text.Lower(Text.Trim(Text.From(target[patch_name]))),
				                        TargetVersion = Text.Trim(Text.From(target[package_version])),
				                        MetadataRows = Record.FieldOrDefault(DebianPackageMetadata, PackageName, {}),
				                        Match = List.First(List.Select(MetadataRows, each Text.From(Record.FieldOrDefault(_, "binary_version", "")) = TargetVersion), null)
				                    in
				                        if Match = null then null else [release = Text.Lower(Text.Trim(Text.From(target[release_codename]))), package_name = PackageName, package_version = TargetVersion, source_package = Text.Lower(Text.Trim(Text.From(Record.FieldOrDefault(Match, "source", "")))), source_version = Text.Trim(Text.From(Record.FieldOrDefault(Match, "version", "")))]
				            )
				        ),
				    FetchDebianTracker = (optional attempt as nullable number) as record =>
				        let
				            CurrentAttempt = if attempt = null then 0 else attempt,
				            Response = try Web.Contents("https://security-tracker.debian.org", [RelativePath = "tracker/data/json", Headers = [Accept = "application/json"], ManualStatusHandling = RetryableStatusCodes]) otherwise null,
				            Status = if Response = null then 0 else Record.FieldOrDefault(Value.Metadata(Response), "Response.Status", 200),
				            Result = if Status = 200 then Json.Document(Response) else if CurrentAttempt < 3 then Function.InvokeAfter(() => @FetchDebianTracker(CurrentAttempt + 1), #duration(0, 0, 0, Number.Power(2, CurrentAttempt + 1))) else error Error.Record("DebianSecurityTrackerUnavailable", "Debian Security Tracker data could not be retrieved after four attempts.", [Status = Status])
				        in
				            Result,
				    DebianTracker = if List.IsEmpty(DebianResolvedTargets) then [] else FetchDebianTracker(),
				    DebianRows =
				        List.Combine(
				            List.Transform(
				                DebianResolvedTargets,
				                (target as record) =>
				                    let
				                        SourcePackage = Text.From(target[source_package]),
				                        SourceVersion = Text.From(target[source_version]),
				                        Release = Text.From(target[release]),
				                        Vulnerabilities = Record.FieldOrDefault(DebianTracker, SourcePackage, []),
				                        VulnerabilityRows = if Vulnerabilities is record then Table.ToRecords(Record.ToTable(Vulnerabilities)) else {}
				                    in
				                        List.RemoveNulls(
				                            List.Transform(
				                                VulnerabilityRows,
				                                (vulnerability as record) =>
				                                    let
				                                        CveId = Text.Upper(Text.Trim(Text.From(vulnerability[Name]))),
				                                        Detail = vulnerability[Value],
				                                        Releases = if Detail is record then Record.FieldOrDefault(Detail, "releases", []) else [],
				                                        ReleaseDetail = if Releases is record then Record.FieldOrDefault(Releases, Release, null) else null,
				                                        Status = if ReleaseDetail is record then Text.Lower(Text.Trim(Text.From(Record.FieldOrDefault(ReleaseDetail, "status", "")))) else "",
				                                        FixedVersion = if ReleaseDetail is record then Text.Trim(Text.From(Record.FieldOrDefault(ReleaseDetail, "fixed_version", ""))) else "",
				                                        Urgency = if ReleaseDetail is record then Text.Proper(Text.Lower(Text.Trim(Text.From(Record.FieldOrDefault(ReleaseDetail, "urgency", "Unknown"))))) else "Unknown"
				                                    in
				                                        if Text.StartsWith(CveId, "CVE-") and Status = "resolved" and FixedVersion <> "" and FixedVersion <> "0" and FixedVersion = SourceVersion then [distribution = "Debian GNU/Linux", release_codename = Release, package_name = Text.From(target[package_name]), package_version = Text.From(target[package_version]), advisory_id = "Debian " & CveId, cve_id = CveId, severity = Urgency, product = SourcePackage, published_at = null, mapping_source = "Debian Security Tracker", source_url = "https://security-tracker.debian.org/tracker/" & CveId] else null
				                            )
				                        )
				            )
				        ),
				    Mappings =
				        Table.FromRecords(
				            List.Combine({UbuntuRows, RedHatRows, DebianRows}),
				            type table [distribution = text, release_codename = text, package_name = text, package_version = text, advisory_id = text, cve_id = text, severity = text, product = text, published_at = nullable datetime, mapping_source = text, source_url = text]
				        ),
				    DistinctMappings = Table.Distinct(Mappings, {"distribution", "release_codename", "package_name", "package_version", "advisory_id", "cve_id"})
				in
				    DistinctMappings
