/// lookup for Azure VMss
table dim_azure_vm_skus
	isHidden

	column memory_gb
		dataType: double
		isHidden
		summarizeBy: sum
		sourceColumn: memory_gb

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vm_sku_key
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: vm_sku_key

		annotation SummarizationSetBy = Automatic

	column vm_sku_name
		dataType: string
		summarizeBy: none
		sourceColumn: vm_sku_name

		annotation SummarizationSetBy = Automatic

	column logical_cores
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: logical_cores

		annotation SummarizationSetBy = Automatic

	partition dim_azure_vm_skus = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    // Load the new CSV generated by the PowerShell script
				    Source = Csv.Document(
				        Web.Contents("https://github.com/Azure/arc_jumpstart_drops/raw/refs/heads/main/ui_dashboard_workbook/arc_pbi_dashboard/artifacts/reference/dim_azure_vm_skus.csv"),
				        [Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.None]
				    ),
				    
				    // Promote headers (vm_sku_key, vm_sku_name, logical_cores, memory_gb)
				    Header = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    
				    // Apply correct data types directly
				    Typed = Table.TransformColumnTypes(Header, {
				        {"vm_sku_key", Int64.Type}, 
				        {"vm_sku_name", type text}, 
				        {"logical_cores", Int64.Type}, 
				        {"memory_gb", type number}
				    }),
				
				    // Helper to normalize strings (maintaining your existing cleanup logic)
				    ToSingleSpaces = (t as nullable text) as nullable text =>
				        if t = null then null else Text.Combine(List.Select(Text.Split(Text.Trim(t), " "), each _ <> ""), " "),
				
				    // Add normalized column for final distinct check
				    WithNorm = Table.AddColumn(Typed, "vm_sku_name_norm", each Text.Lower(ToSingleSpaces([vm_sku_name])), type text),
				
				    // Final safety check: Keep first per normalized name (in case of regional duplicates in source)
				    FirstPerSku = Table.Distinct(WithNorm, {"vm_sku_name_norm"}),
				
				    // Select the final clean columns
				    Final = Table.SelectColumns(FirstPerSku, {"vm_sku_key", "vm_sku_name", "logical_cores", "memory_gb"})
				in
				    Final
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

