table dim_extension_types
	isHidden

	column extension_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: extension_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column extension_display_name
		dataType: string
		isHidden
		isDefaultLabel
		summarizeBy: none
		sourceColumn: extension_display_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column extension_short_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: extension_short_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column os_type
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: os_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_sql
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: is_sql

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column extension_type_key
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: sum
		sourceColumn: extension_type_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column in_dashbaord
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: in_dashbaord

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_extension_types = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    // 1. Pull the data
				    Source = Csv.Document(
				        Web.Contents("https://raw.githubusercontent.com/Azure/arc_jumpstart_drops/refs/heads/main/ui_dashboard_workbook/arc_pbi_dashboard/artifacts/reference/dim_extension_types.csv"),
				        [Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]
				    ),
				    
				    // 2. Promote Headers
				    Header = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    
				    // 3. Add Index (Surrogate Key)
				    AddKey = Table.AddIndexColumn(Header, "extension_type_key", 1, 1, Int64.Type),
				
				    // 4. Type Casting (Crucial for performance in visuals)
				    // Replace "Column Name" with your actual column names
				    Typed = Table.TransformColumnTypes(AddKey, {
				        {"extension_type_key", Int64.Type}
				        // Add other columns here, e.g., {"ExtensionName", type text}
				    })
				in
				    Typed
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

