table dim_sql_patches
	isHidden

	column sql_version_number
		dataType: string
		isHidden
		isDefaultLabel
		summarizeBy: none
		sourceColumn: sql_version_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column service_pack
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: service_pack

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column update
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: update

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column kb_number
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: kb_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column release_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		summarizeBy: none
		sourceColumn: release_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column patch_index
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: patch_index

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column sql_version
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: sql_version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_sql_patches = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Lines.FromBinary(
				        Web.Contents(
				            "https://learn.microsoft.com/en-us/troubleshoot/sql/releases/download-and-install-latest-updates",
				            [Headers = [Accept = "text/markdown"]]
				        ),
				        null,
				        null,
				        TextEncoding.Utf8
				    ),
				
				    ExtractVersionTable = (version as text) as table =>
				        let
				            Heading = "### " & version,
				            HeadingIndex = List.PositionOf(Source, Heading),
				            Remaining = if HeadingIndex >= 0 then List.Skip(Source, HeadingIndex + 1) else {},
				            HeaderIndex = List.PositionOf(List.Transform(Remaining, each Text.StartsWith(Text.Trim(_), "| Build number or version")), true),
				            CandidateLines = if HeaderIndex >= 0 then List.Skip(Remaining, HeaderIndex) else {},
				            TableLines = List.FirstN(CandidateLines, each Text.StartsWith(Text.Trim(_), "|")),
				            DataLines = if List.Count(TableLines) >= 2 then List.Skip(TableLines, 2) else {},
				            ParseRow = (line as text) as list =>
				                List.Transform(
				                    Text.Split(Text.Range(Text.Trim(line), 1, Text.Length(Text.Trim(line)) - 2), "|"),
				                    each Text.Trim(_)
				                ),
				            Rows = List.Transform(DataLines, each ParseRow(_)),
				            RawTable = Table.FromRows(Rows, {"sql_version_number", "service_pack", "update", "kb_number", "release_date"}),
				            CleanKb = Table.TransformColumns(RawTable, {{"kb_number", each if Text.StartsWith(_, "[") then Text.BetweenDelimiters(_, "[", "]") else _, type text}}),
				            Typed = Table.TransformColumnTypes(CleanKb, {{"sql_version_number", type text}, {"service_pack", type text}, {"update", type text}, {"kb_number", type text}, {"release_date", type date}}, "en-US"),
				            DistinctRows = Table.Distinct(Typed, {"sql_version_number"}),
				            Indexed = Table.AddIndexColumn(DistinctRows, "patch_index", 1, 1, Int64.Type),
				            Tagged = Table.AddColumn(Indexed, "sql_version", each version, type text)
				        in
				            Tagged,
				
				    CombinedTables = Table.Combine({
				        ExtractVersionTable("SQL Server 2025"),
				        ExtractVersionTable("SQL Server 2022"),
				        ExtractVersionTable("SQL Server 2019"),
				        ExtractVersionTable("SQL Server 2017"),
				        ExtractVersionTable("SQL Server 2016"),
				        ExtractVersionTable("SQL Server 2014"),
				        ExtractVersionTable("SQL Server 2012"),
				        ExtractVersionTable("SQL Server 2008 R2"),
				        ExtractVersionTable("SQL Server 2008")
				    })
				in
				    CombinedTables

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
