/// Single-row customer-owned licensing declaration used to assess Software Assurance and Azure Hybrid Benefit eligibility without inferring entitlement from Arc billing metadata.
table licensing_declaration
	lineageTag: 6dc6949a-a051-468d-9c98-eb8bc517a357

	/// Customer-declared Software Assurance status; never inferred from Arc billing mode.
	column software_assurance_status
		dataType: string
		lineageTag: e7328d27-3f36-4971-8277-12f948e9fd1b
		summarizeBy: none
		sourceColumn: software_assurance_status

	/// Declared Standard edition cores covered by active Software Assurance.
	column standard_sa_cores
		dataType: int64
		isHidden
		lineageTag: e1c86643-3260-4971-bcf9-6e170b4705ea
		summarizeBy: none
		sourceColumn: standard_sa_cores

	/// Declared Enterprise edition cores covered by active Software Assurance.
	column enterprise_sa_cores
		dataType: int64
		isHidden
		lineageTag: fe6e02ac-5d4d-4979-a609-dbf534b39cc3
		summarizeBy: none
		sourceColumn: enterprise_sa_cores

	/// Customer-provided evidence source for the licensing declaration.
	column evidence_source
		dataType: string
		lineageTag: 33b039c9-ac02-43e8-a42d-c1ee97b4cf2a
		summarizeBy: none
		sourceColumn: evidence_source

	/// Effective date of the licensing declaration.
	column effective_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 4ec48641-ed21-42cd-a081-694ba27e5584
		summarizeBy: none
		sourceColumn: effective_date

	/// Assessment run or evidence-set identifier for the licensing declaration.
	column assessment_run
		dataType: string
		lineageTag: cebeab59-a9a1-4164-bf30-de912efd19e3
		summarizeBy: none
		sourceColumn: assessment_run

	/// Confidence based on declaration completeness and evidence metadata.
	column declaration_confidence
		dataType: string
		lineageTag: 087c838d-23f6-4217-a3e2-0d66800f4373
		summarizeBy: none
		sourceColumn: declaration_confidence

	partition licensing_declaration = m
		mode: import
		source =
				let
				    NormalizeText = (value as any, fallback as text) as text =>
				        let candidate = try Text.Trim(Text.From(value)) otherwise ""
				        in if candidate = "" then fallback else candidate,
				    StatusInput = Text.Lower(NormalizeText(Licensing_SA_Status, "Unknown")),
				    SoftwareAssuranceStatus =
				        if List.Contains({"confirmed", "yes", "active", "enabled"}, StatusInput) then "Confirmed"
				        else if List.Contains({"not confirmed", "no", "none", "not active", "disabled"}, StatusInput) then "Not confirmed"
				        else "Unknown",
				    ParseCores = (value as any) as nullable number =>
				        let parsed = try Number.RoundDown(Number.FromText(Text.Trim(Text.From(value)), "en-GB")) otherwise null
				        in if parsed = null or parsed < 0 then null else parsed,
				    StandardCores = ParseCores(Licensing_Standard_SA_Cores),
				    EnterpriseCores = ParseCores(Licensing_Enterprise_SA_Cores),
				    EffectiveDateText = NormalizeText(Licensing_Effective_Date, "Not provided"),
				    EffectiveDate = try Date.FromText(EffectiveDateText, [Format="yyyy-MM-dd", Culture="en-GB"]) otherwise null,
				    Raw = #table(
				        type table [
				            software_assurance_status = text,
				            standard_sa_cores = nullable number,
				            enterprise_sa_cores = nullable number,
				            evidence_source = text,
				            effective_date = nullable date,
				            assessment_run = text,
				            declaration_confidence = text
				        ],
				        {{
				            SoftwareAssuranceStatus,
				            StandardCores,
				            EnterpriseCores,
				            NormalizeText(Licensing_Evidence_Source, "Not provided"),
				            EffectiveDate,
				            NormalizeText(Licensing_Assessment_Run, "Not provided"),
				            if SoftwareAssuranceStatus = "Confirmed" and StandardCores <> null and EnterpriseCores <> null and NormalizeText(Licensing_Evidence_Source, "Not provided") <> "Not provided" then "High"
				            else if SoftwareAssuranceStatus = "Not confirmed" then "High"
				            else "Low"
				        }}
				    ),
				    Source = Table.TransformColumnTypes(
				        Raw,
				        {
				            {"standard_sa_cores", Int64.Type},
				            {"enterprise_sa_cores", Int64.Type}
				        }
				    )
				in
				    Source
