/// Single-row trusted customer input used to compare owned Software Assurance cores with current and forecast Azure Hybrid Benefit demand.
table licensing_inputs
	lineageTag: 6dc6949a-a051-468d-9c98-eb8bc517a357

	/// Customer-owned Standard edition cores covered by active Software Assurance.
	column standard_sa_cores
		dataType: int64
		isHidden
		lineageTag: e1c86643-3260-4971-bcf9-6e170b4705ea
		summarizeBy: none
		sourceColumn: standard_sa_cores

	/// Customer-owned Enterprise edition cores covered by active Software Assurance.
	column enterprise_sa_cores
		dataType: int64
		isHidden
		lineageTag: fe6e02ac-5d4d-4979-a609-dbf534b39cc3
		summarizeBy: none
		sourceColumn: enterprise_sa_cores

	/// Optional annualized customer price per Standard core for a new licence with Software Assurance.
	column standard_license_sa_annual_cost_per_core
		dataType: decimal
		isHidden
		lineageTag: 82499478-642e-4c6f-bb72-b2038200c005
		summarizeBy: none
		sourceColumn: standard_license_sa_annual_cost_per_core

	/// Optional annualized customer price per Enterprise core for a new licence with Software Assurance.
	column enterprise_license_sa_annual_cost_per_core
		dataType: decimal
		isHidden
		lineageTag: 4ec3102f-d8ce-4418-9341-e22ac80a451e
		summarizeBy: none
		sourceColumn: enterprise_license_sa_annual_cost_per_core

	partition licensing_inputs = m
		mode: import
		source =
				let
				    ParseCores = (value as any) as number =>
				        let parsed = try Number.RoundDown(Number.FromText(Text.Trim(Text.From(value)), "en-GB")) otherwise 0
				        in if parsed < 0 then 0 else parsed,
				    ParseOptionalCost = (value as any) as nullable number =>
				        let parsed = try Number.FromText(Text.Trim(Text.From(value)), "en-GB") otherwise null
				        in if parsed = null or parsed < 0 then null else parsed,
				    Raw = #table(
				        type table [
				            standard_sa_cores = number,
				            enterprise_sa_cores = number,
				            standard_license_sa_annual_cost_per_core = nullable number,
				            enterprise_license_sa_annual_cost_per_core = nullable number
				        ],
				        {{
				            ParseCores(Licensing_Standard_SA_Cores),
				            ParseCores(Licensing_Enterprise_SA_Cores),
				            ParseOptionalCost(Licensing_Standard_License_SA_Annual_Cost_Per_Core),
				            ParseOptionalCost(Licensing_Enterprise_License_SA_Annual_Cost_Per_Core)
				        }}
				    ),
				    Source = Table.TransformColumnTypes(
				        Raw,
				        {
				            {"standard_sa_cores", Int64.Type},
				            {"enterprise_sa_cores", Int64.Type},
				            {"standard_license_sa_annual_cost_per_core", Currency.Type},
				            {"enterprise_license_sa_annual_cost_per_core", Currency.Type}
				        }
				    )
				in
				    Source
